# Generated by Django 4.0.4 on 2022-05-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Псевдоним')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('intro_text', models.TextField(blank=True, verbose_name='Аннотация')),
                ('full_text', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован?')),
                ('views', models.IntegerField(default=0, verbose_name='Хиты')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Услуга(у)',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('title_menu', models.CharField(max_length=255, verbose_name='Название в меню')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение!!')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Рубрика(ю)',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Псевдоним')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('intro_text', models.TextField(blank=True, verbose_name='Аннотация')),
                ('full_text', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views', models.IntegerField(default=0, verbose_name='Хиты')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Услуга(у)',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_seo', models.CharField(blank=True, max_length=255, verbose_name='Заголовок для меню')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Псевдоним')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('intro_text', models.TextField(blank=True, verbose_name='Аннотация')),
                ('full_text', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views', models.IntegerField(default=0, verbose_name='Хиты')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('feature', models.BooleanField(default=False, verbose_name='Рекомендуем')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_rubric', to='cms.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Страница(у)',
                'verbose_name_plural': 'Страницы',
                'ordering': ['-created_at'],
            },
        ),
    ]
