# Generated by Django 4.0.1 on 2022-04-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('title_menu', models.CharField(max_length=255, verbose_name='Название в меню')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение!!')),
                ('visible', models.IntegerField(default=1, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Категория(ю)',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_seo', models.CharField(blank=True, max_length=255, verbose_name='Заголовок для меню')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Псевдоним')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('intro_text', models.TextField(blank=True, verbose_name='Аннотация')),
                ('full_text', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views', models.IntegerField(default=0, verbose_name='Хиты')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='page', to='portal.author', verbose_name='Автор')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.rubric', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Страница(у)',
                'verbose_name_plural': 'Страницы',
                'ordering': ['-created_at'],
            },
        ),
    ]
